### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by AIXjing** [AIXjing/juicefs#2]
Create new buckets with different public permission and install juicefs.

**Comment by liufuyang** [comment]
A few more things to do/test:
- [ ] update doc to include a part on installing https://osxfuse.github.io/ (in case one is using a mac)
- [ ] perhaps write a few more lines on amazon S3 connection url (difficult/cannot find url on aws pages)
- [ ] test using a redis instead of local db
- [ ] test using postgres instead of local db
- [x] test using GCP's GCS and redis/postgres (using json key file?)
- [ ] test using colab
- [ ] optimize docs of how to use juiceFS on [Google Cloud Storage](https://juicefs.com/docs/community/how_to_setup_object_storage/#google-cloud-storage)

**Comment by AIXjing** [comment]
change the bucket address from https://myjuicefs.s3.us-east-2.amazonaws.com to http://
